version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db-todolist'
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "${PG_PORT}:${PG_PORT}"

  redis:
    image: 'redis:latest'
    container_name: 'redis-todolist'
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      
volumes:
    nodemodules: {}